#!/bin/bash
readonly ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
docker build -f $ROOT/Dockerfile.oracle-jdk -t islandora/claw-maven:oracle-jdk $ROOT
docker build -f $ROOT/Dockerfile.open-jdk -t islandora/claw-maven:open-jdk $ROOT
# Open JDK is the default implementation. 
docker tag islandora/claw-maven:open-jdk islandora/claw-maven:latest
